# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import annotations_pb2 as schema_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0csimple.proto\x1a\x18schema/annotations.proto\"\x1c\n\x06\x45ntity\x12\x12\n\x02id\x18\x01 \x01(\tB\x06\xea\xf4\x18\x02\x08\x01\"\xf1\x01\n\x0cHelloRequest\x12\x14\n\x04name\x18\x01 \x01(\tB\x06\xea\xf4\x18\x02\x08\x02\x12\x15\n\x03\x61ge\x18\x02 \x01(\x05\x42\x08\xea\xf4\x18\x04*\x02\x08\x05\x12\x1c\n\x14no_validation_schema\x18\x03 \x01(\t\x12\x16\n\x04tags\x18\x04 \x03(\tB\x08\xea\xf4\x18\x04\x10\nP\x03\x12\x35\n\x05\x63odes\x18\x05 \x03(\x0b\x32\x18.HelloRequest.CodesEntryB\x0c\xea\xf4\x18\x02P\x02\xea\xf4\x18\x02\x08\x64\x12\x19\n\x08\x65ntities\x18\x06 \x03(\x0b\x32\x07.Entity\x1a,\n\nCodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[schema_dot_annotations__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Entity.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\002\010\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=70,
)


_HELLOREQUEST_CODESENTRY = _descriptor.Descriptor(
  name='CodesEntry',
  full_name='HelloRequest.CodesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='HelloRequest.CodesEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='HelloRequest.CodesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=314,
)

_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\002\010\002'))),
    _descriptor.FieldDescriptor(
      name='age', full_name='HelloRequest.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\004*\002\010\005'))),
    _descriptor.FieldDescriptor(
      name='no_validation_schema', full_name='HelloRequest.no_validation_schema', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='HelloRequest.tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\004\020\nP\003'))),
    _descriptor.FieldDescriptor(
      name='codes', full_name='HelloRequest.codes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\002P\002\352\364\030\002\010d'))),
    _descriptor.FieldDescriptor(
      name='entities', full_name='HelloRequest.entities', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HELLOREQUEST_CODESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=314,
)

_HELLOREQUEST_CODESENTRY.containing_type = _HELLOREQUEST
_HELLOREQUEST.fields_by_name['codes'].message_type = _HELLOREQUEST_CODESENTRY
_HELLOREQUEST.fields_by_name['entities'].message_type = _ENTITY
DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), dict(
  DESCRIPTOR = _ENTITY,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:Entity)
  ))
_sym_db.RegisterMessage(Entity)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(

  CodesEntry = _reflection.GeneratedProtocolMessageType('CodesEntry', (_message.Message,), dict(
    DESCRIPTOR = _HELLOREQUEST_CODESENTRY,
    __module__ = 'simple_pb2'
    # @@protoc_insertion_point(class_scope:HelloRequest.CodesEntry)
    ))
  ,
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)
_sym_db.RegisterMessage(HelloRequest.CodesEntry)


_ENTITY.fields_by_name['id'].has_options = True
_ENTITY.fields_by_name['id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\002\010\001'))
_HELLOREQUEST_CODESENTRY.has_options = True
_HELLOREQUEST_CODESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_HELLOREQUEST.fields_by_name['name'].has_options = True
_HELLOREQUEST.fields_by_name['name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\002\010\002'))
_HELLOREQUEST.fields_by_name['age'].has_options = True
_HELLOREQUEST.fields_by_name['age']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\004*\002\010\005'))
_HELLOREQUEST.fields_by_name['tags'].has_options = True
_HELLOREQUEST.fields_by_name['tags']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\004\020\nP\003'))
_HELLOREQUEST.fields_by_name['codes'].has_options = True
_HELLOREQUEST.fields_by_name['codes']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\352\364\030\002P\002\352\364\030\002\010d'))
# @@protoc_insertion_point(module_scope)
